In [1]:
import numpy as np

np_list = np.array([1,2,3])


In [2]:
np_list

array([1, 2, 3])

In [3]:
print(np_list)

[1 2 3]


In [ ]:
array_2d = np.array([[56,5.8,120], 
                    [12,6,100], 
                     [41,5,120], 
                     [23,5.7,135]])


(4, 3)

In [20]:
array_2d.shape

(4, 3)

In [5]:
print(np.array)

<built-in function array>


In [6]:
print(array_2d)

[[ 56.    5.8 120. ]
 [ 12.    6.  100. ]
 [ 41.    5.  120. ]
 [ 23.    5.7 135. ]]


In [ ]:
array_3d = np.ones((2,2,3))


(2, 2, 3)

In [21]:
array_3d.shape


(2, 2, 3)

In [8]:
print(array_3d)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [10]:
array_2d.shape

(4, 3)

In [12]:
array_2d.dtype.name

'float64'

In [13]:
array_2d.size

12

In [14]:
print(array_3d)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [15]:
array_2d.size

12

In [16]:
print(2d_array)

SyntaxError: invalid syntax (<ipython-input-16-15d4f8572cc1>, line 1)

In [19]:
print(np.array)

<built-in function array>


In [23]:
nextArray = np.arange(0,10)

In [24]:
print(nextArray)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
nextArray.shape

(10,)

In [26]:
anotherArray = np.linspace(0,10,50)

In [27]:
anotherArray

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [28]:
newArrayAgain = np.ones((3,4))

In [29]:
newArrayAgain

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
arr = np.arange(0,25)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
arr[8]

8

In [33]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [34]:
array_2d = np.array([[56,5.8,120], 
                    [12,6,100], 
                     [41,5,120], 
                     [23,5.7,135]])

In [35]:
array_2d

array([[ 56. ,   5.8, 120. ],
       [ 12. ,   6. , 100. ],
       [ 41. ,   5. , 120. ],
       [ 23. ,   5.7, 135. ]])

In [37]:
array_2d[2][1]

5.0

In [39]:
array_2d[2,:]

array([ 41.,   5., 120.])

In [40]:
array_2d[:2, 1:3]

array([[  5.8, 120. ],
       [  6. , 100. ]])

In [43]:
array_2d[:,2]

array([120., 100., 120., 135.])

In [44]:
array_2d[:,1:3]

array([[  5.8, 120. ],
       [  6. , 100. ],
       [  5. , 120. ],
       [  5.7, 135. ]])

In [45]:
new_array_2d = array_2d.copy()

In [46]:
new_array_2d[:,:] = 99

In [47]:
new_array_2d

array([[99., 99., 99.],
       [99., 99., 99.],
       [99., 99., 99.],
       [99., 99., 99.]])

In [50]:
a = np.log(new_array_2d)

In [51]:
a

array([[4.59511985, 4.59511985, 4.59511985],
       [4.59511985, 4.59511985, 4.59511985],
       [4.59511985, 4.59511985, 4.59511985],
       [4.59511985, 4.59511985, 4.59511985]])

In [52]:
trans_array_2d = new_array_2d.T

In [53]:
trans_array_2d

array([[99., 99., 99., 99.],
       [99., 99., 99., 99.],
       [99., 99., 99., 99.]])